set(DOCA_ROOT "" CACHE PATH "Extracted or installed DOCA SDK prefix")
if(NOT DOCA_ROOT)
  message(FATAL_ERROR "ANNS_DOCA requires explicit DOCA_ROOT; no simulated fallback")
endif()
find_path(DOCA_INCLUDE doca_dma.h PATHS "${DOCA_ROOT}/include" NO_DEFAULT_PATH NO_CMAKE_FIND_ROOT_PATH REQUIRED)
if(CMAKE_SYSTEM_PROCESSOR MATCHES "aarch64|arm64")
  set(DOCA_ARCH aarch64-linux-gnu)
else()
  set(DOCA_ARCH x86_64-linux-gnu)
endif()
foreach(component common dma comch)
  find_library(DOCA_${component} NAMES doca_${component} PATHS "${DOCA_ROOT}/lib/${DOCA_ARCH}" NO_DEFAULT_PATH NO_CMAKE_FIND_ROOT_PATH REQUIRED)
endforeach()
add_library(anns_doca_backend src/transport/doca/backend.cpp)
target_include_directories(anns_doca_backend SYSTEM PRIVATE "${DOCA_INCLUDE}")
target_compile_definitions(anns_doca_backend PRIVATE ALLOW_EXPERIMENTAL_API)
target_link_libraries(anns_doca_backend PUBLIC anns_runtime "${DOCA_common}" "${DOCA_dma}" "${DOCA_comch}")
foreach(app host soc)
  add_executable(anns_${app} apps/${app}_main.cpp)
  target_link_libraries(anns_${app} PRIVATE anns_doca_backend anns_report)
endforeach()
# The selected SDK headers and libraries must also build a standalone API check.
add_executable(anns_sdk_check tests/sdk_check.cpp)
target_include_directories(anns_sdk_check SYSTEM PRIVATE "${DOCA_INCLUDE}")
target_link_libraries(anns_sdk_check PRIVATE "${DOCA_common}" "${DOCA_dma}" "${DOCA_comch}")
